# Generated by Django 4.2.16 on 2024-10-19 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
